title: Eduardo Cuducos
description: Sociologist, geek, bread baker, and sports fan.
baseurl: ""
url: "https://cuducos.me"
paginate: 21
paginate_path: "/blog/:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-srcset-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files:
  - media

srcset:
  source: _media
  output: media
