source 'https://rubygems.org'
ruby '2.5.1'

gem 'bitters', '~> 1.2'
gem 'bourbon', '~> 4.3.4'
gem 'jekyll', '~> 3.8.3'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'jekyll-sitemap', '~> 1.2.0'
gem 'jekyll-srcset-tag', '~> 0.2.0'
gem 'neat', '~> 1.9.1'
